<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class SetepakProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vendorId = 2; // Setepak Printing Service KTF

        $products = [
            [
                'name' => 'Stickers & Labels - Small',
                'slug' => 'stickers-labels-small',
                'thumb_image' => 'stickers-small.png',
                'vendor_id' => $vendorId,
                'category_id' => 8, // Printing category
                'brand_id' => 3, // Setepak brand
                'qty' => 1000,
                'short_description' => 'High-quality stickers and labels for various purposes.',
                'long_description' => 'High-quality stickers and labels for various purposes. Small size with different material options.',
                'price' => 0.50,
                'status' => 1,
            ],
            [
                'name' => 'Stickers & Labels - Large',
                'slug' => 'stickers-labels-large',
                'thumb_image' => 'stickers-large.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 500,
                'short_description' => 'Premium stickers and labels for branding.',
                'long_description' => 'Premium stickers and labels for branding and identification. Large size with durable materials.',
                'price' => 5.00,
                'status' => 1,
            ],
            [
                'name' => 'A4 Black & White Prints',
                'slug' => 'a4-black-white-prints',
                'thumb_image' => 'a4-bw-print.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 2000,
                'short_description' => 'Standard A4 black and white printing.',
                'long_description' => 'Standard A4 black and white printing service for documents and reports.',
                'price' => 1.00,
                'status' => 1,
            ],
            [
                'name' => 'A4 Color Prints',
                'slug' => 'a4-color-prints',
                'thumb_image' => 'a4-color-print.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 1500,
                'short_description' => 'High-quality A4 color printing.',
                'long_description' => 'High-quality A4 color printing for presentations and marketing materials.',
                'price' => 5.00,
                'status' => 1,
            ],
            [
                'name' => 'A3 Black & White Prints',
                'slug' => 'a3-black-white-prints',
                'thumb_image' => 'a3-bw-print.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 800,
                'short_description' => 'Large format A3 black and white printing.',
                'long_description' => 'Large format A3 black and white printing for posters and technical drawings.',
                'price' => 3.00,
                'status' => 1,
            ],
            [
                'name' => 'A3 Color Prints',
                'slug' => 'a3-color-prints',
                'thumb_image' => 'a3-color-print.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 600,
                'short_description' => 'Premium A3 color printing.',
                'long_description' => 'Premium A3 color printing for large format presentations and displays.',
                'price' => 10.00,
                'status' => 1,
            ],
            [
                'name' => 'Business Cards - Basic Set',
                'slug' => 'business-cards-basic',
                'thumb_image' => 'business-cards-basic.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 200,
                'short_description' => 'Professional business cards set (100 pieces).',
                'long_description' => 'Professional business cards set (100 pieces) with standard design and materials.',
                'price' => 20.00,
                'status' => 1,
            ],
            [
                'name' => 'Business Cards - Premium Set',
                'slug' => 'business-cards-premium',
                'thumb_image' => 'business-cards-premium.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 100,
                'short_description' => 'Premium business cards set (500 pieces).',
                'long_description' => 'Premium business cards set (500 pieces) with high-quality materials and finishes.',
                'price' => 100.00,
                'status' => 1,
            ],
            [
                'name' => 'Small Banner',
                'slug' => 'small-banner',
                'thumb_image' => 'small-banner.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 150,
                'short_description' => 'Small size banner for indoor advertising.',
                'long_description' => 'Small size banner for indoor advertising and promotional purposes.',
                'price' => 30.00,
                'status' => 1,
            ],
            [
                'name' => 'Large Banner',
                'slug' => 'large-banner',
                'thumb_image' => 'large-banner.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 50,
                'short_description' => 'Large format banner with weather-resistant materials.',
                'long_description' => 'Large format banner with weather-resistant materials for outdoor advertising.',
                'price' => 200.00,
                'status' => 1,
            ],
            [
                'name' => 'Flyers - Small Batch',
                'slug' => 'flyers-small-batch',
                'thumb_image' => 'flyers-small.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 300,
                'short_description' => 'Professional flyers printing (50-100 pieces).',
                'long_description' => 'Professional flyers printing service for small batch orders (50-100 pieces).',
                'price' => 50.00,
                'status' => 1,
            ],
            [
                'name' => 'Brochures - Large Batch',
                'slug' => 'brochures-large-batch',
                'thumb_image' => 'brochures-large.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 100,
                'short_description' => 'High-quality brochures (500+ pieces).',
                'long_description' => 'High-quality brochures with glossy finish for large batch orders (500+ pieces).',
                'price' => 300.00,
                'status' => 1,
            ],
            [
                'name' => 'T-shirt Printing - Basic',
                'slug' => 't-shirt-printing-basic',
                'thumb_image' => 't-shirt-basic.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 400,
                'short_description' => 'Basic t-shirt printing with simple design.',
                'long_description' => 'Basic t-shirt printing with simple design and standard materials.',
                'price' => 20.00,
                'status' => 1,
            ],
            [
                'name' => 'T-shirt Printing - Premium',
                'slug' => 't-shirt-printing-premium',
                'thumb_image' => 't-shirt-premium.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 200,
                'short_description' => 'Premium t-shirt printing with complex design.',
                'long_description' => 'Premium t-shirt printing with complex design and high-quality materials.',
                'price' => 50.00,
                'status' => 1,
            ],
            [
                'name' => 'Photocopying - Black & White',
                'slug' => 'photocopying-black-white',
                'thumb_image' => 'photocopy-bw.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 5000,
                'short_description' => 'Standard black and white photocopying per page.',
                'long_description' => 'Standard black and white photocopying service per page.',
                'price' => 0.10,
                'status' => 1,
            ],
            [
                'name' => 'Photocopying - Color',
                'slug' => 'photocopying-color',
                'thumb_image' => 'photocopy-color.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 3000,
                'short_description' => 'High-quality color photocopying per page.',
                'long_description' => 'High-quality color photocopying service per page.',
                'price' => 0.50,
                'status' => 1,
            ],
            [
                'name' => 'Custom Packaging - Simple',
                'slug' => 'custom-packaging-simple',
                'thumb_image' => 'packaging-simple.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 500,
                'short_description' => 'Simple custom packaging design.',
                'long_description' => 'Simple custom packaging design for small items and basic requirements.',
                'price' => 5.00,
                'status' => 1,
            ],
            [
                'name' => 'Custom Packaging - Complex',
                'slug' => 'custom-packaging-complex',
                'thumb_image' => 'packaging-complex.png',
                'vendor_id' => $vendorId,
                'category_id' => 8,
                'brand_id' => 3,
                'qty' => 100,
                'short_description' => 'Complex custom packaging with advanced design.',
                'long_description' => 'Complex custom packaging with advanced design and premium materials.',
                'price' => 50.00,
                'status' => 1,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
