<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class UTMMartProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */    public function run()
    {
        $products = [
            [
                'name' => 'Baseball Cap',
                'slug' => 'baseball-cap',
                'thumb_image' => 'images/utmmart/baseball.png',
                'vendor_id' => 1, // UTM Mart vendor ID
                'category_id' => 1, // Apparel category
                'brand_id' => 1, // UTM brand
                'qty' => 50,
                'short_description' => 'UTM branded baseball cap',
                'long_description' => 'Stylish UTM branded baseball cap, perfect for sunny days on campus.',
                'price' => 24.00,
                'status' => 1,
            ],
            [
                'name' => 'Trucker Cap',
                'slug' => 'trucker-cap',
                'thumb_image' => 'images/utmmart/trucker.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 50,
                'short_description' => 'UTM branded trucker cap',
                'long_description' => 'Comfortable mesh-back trucker cap with UTM logo.',
                'price' => 22.00,
                'status' => 1,
            ],
            [
                'name' => 'Gel Ink Pen',
                'slug' => 'gel-ink-pen',
                'thumb_image' => 'images/utmmart/gelpen.png',
                'vendor_id' => 1,
                'category_id' => 3, // Stationery category
                'brand_id' => 1,
                'qty' => 200,
                'short_description' => 'UTM branded gel ink pen',
                'long_description' => 'Smooth writing gel ink pen with UTM branding.',
                'price' => 3.90,
                'status' => 1,
            ],
            [
                'name' => 'Glass Mug',
                'slug' => 'glass-mug',
                'thumb_image' => 'images/utmmart/glassmug.png',
                'vendor_id' => 1,
                'category_id' => 2, // Drinkware category
                'brand_id' => 1,
                'qty' => 75,
                'short_description' => 'UTM branded glass mug',
                'long_description' => 'Elegant glass mug with UTM logo, perfect for hot or cold beverages.',
                'price' => 10.00,
                'status' => 1,
            ],
            [
                'name' => 'Tumbler',
                'slug' => 'tumbler',
                'thumb_image' => 'images/utmmart/tumbler.png',
                'vendor_id' => 1,
                'category_id' => 2,
                'brand_id' => 1,
                'qty' => 60,
                'short_description' => 'UTM branded tumbler',
                'long_description' => 'Insulated tumbler with UTM logo, keeps drinks hot or cold for hours.',
                'price' => 35.00,
                'status' => 1,
            ],
            [
                'name' => 'Flask Set',
                'slug' => 'flask-set',
                'thumb_image' => 'images/utmmart/flaskset.png',
                'vendor_id' => 1,
                'category_id' => 2,
                'brand_id' => 1,
                'qty' => 40,
                'short_description' => 'UTM branded flask set',
                'long_description' => 'Complete flask set with UTM branding, includes flask and cups.',
                'price' => 42.00,
                'status' => 1,
            ],
            [
                'name' => 'Paper Bag',
                'slug' => 'paper-bag',
                'thumb_image' => 'images/utmmart/paperbag.png',
                'vendor_id' => 1,
                'category_id' => 4, // Bags category
                'brand_id' => 1,
                'qty' => 300,
                'short_description' => 'UTM branded paper bag',
                'long_description' => 'Eco-friendly paper bag with UTM logo.',
                'price' => 7.00,
                'status' => 1,
            ],
            [
                'name' => 'Tote Bag',
                'slug' => 'tote-bag',
                'thumb_image' => 'images/utmmart/totebag.png',
                'vendor_id' => 1,
                'category_id' => 4,
                'brand_id' => 1,
                'qty' => 120,
                'short_description' => 'UTM branded tote bag',
                'long_description' => 'Spacious and durable tote bag with UTM logo, perfect for carrying books or shopping.',
                'price' => 7.00,
                'status' => 1,
            ],
            [
                'name' => 'Woven Bag',
                'slug' => 'woven-bag',
                'thumb_image' => 'images/utmmart/wovenbag.png',
                'vendor_id' => 1,
                'category_id' => 4,
                'brand_id' => 1,
                'qty' => 100,
                'short_description' => 'UTM branded woven bag',
                'long_description' => 'High quality woven bag with UTM branding, stylish and practical.',
                'price' => 8.00,
                'status' => 1,
            ],
            [
                'name' => 'Non-Woven Bag',
                'slug' => 'non-woven-bag',
                'thumb_image' => 'images/utmmart/nonwovenbag.png',
                'vendor_id' => 1,
                'category_id' => 4,
                'brand_id' => 1,
                'qty' => 150,
                'short_description' => 'UTM branded non-woven bag',
                'long_description' => 'Lightweight non-woven fabric bag with UTM logo, eco-friendly and reusable.',
                'price' => 5.00,
                'status' => 1,
            ],
            [
                'name' => 'Crystal Plaque with Laser Print',
                'slug' => 'crystal-plaque-laser',
                'thumb_image' => 'images/utmmart/crystal.png',
                'vendor_id' => 1,
                'category_id' => 5, // Awards & Recognition category
                'brand_id' => 1,
                'qty' => 30,
                'short_description' => 'UTM branded crystal plaque with laser print',
                'long_description' => 'Elegant crystal plaque with laser-engraved UTM logo, perfect for awards or recognition.',
                'price' => 55.00,
                'status' => 1,
            ],
            [
                'name' => 'Crystal Plaque with Colour Print',
                'slug' => 'crystal-plaque-colour',
                'thumb_image' => 'images/utmmart/crystalpl.png',
                'vendor_id' => 1,
                'category_id' => 5,
                'brand_id' => 1,
                'qty' => 25,
                'short_description' => 'UTM branded crystal plaque with colour print',
                'long_description' => 'Premium crystal plaque with full-color UTM logo printing, ideal for special recognition.',
                'price' => 65.00,
                'status' => 1,
            ],
            [
                'name' => 'UTM Hoodie',
                'slug' => 'utm-hoodie',
                'thumb_image' => 'images/utmmart/hoodies.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 70,
                'short_description' => 'UTM branded hoodie',
                'long_description' => 'Warm and comfortable hoodie with UTM logo, perfect for cool weather on campus.',
                'price' => 100.00,
                'status' => 1,
            ],
            [
                'name' => 'Bomber Jacket',
                'slug' => 'bomber-jacket',
                'thumb_image' => 'images/utmmart/bomberjacket.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 50,
                'short_description' => 'UTM branded bomber jacket',
                'long_description' => 'Stylish bomber jacket with UTM branding, perfect for casual wear.',
                'price' => 100.00,
                'status' => 1,
            ],
            [
                'name' => 'Sublimation Shirt',
                'slug' => 'sublimation-shirt',
                'thumb_image' => 'images/utmmart/sub.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 100,
                'short_description' => 'UTM sublimation shirt',
                'long_description' => 'High-quality sublimation shirt with vibrant UTM design that won\'t fade.',
                'price' => 50.00,
                'status' => 1,
            ],
            [
                'name' => 'Muslimah Shirt White',
                'slug' => 'muslimah-shirt-white',
                'thumb_image' => 'images/utmmart/musl.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 80,
                'short_description' => 'UTM white muslimah shirt',
                'long_description' => 'Modest and comfortable white muslimah shirt with UTM branding.',
                'price' => 45.00,
                'status' => 1,
            ],
            [
                'name' => 'Long Sleeved Sublimation Shirt',
                'slug' => 'long-sleeved-sublimation',
                'thumb_image' => 'images/utmmart/longsleeved sub.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 90,
                'short_description' => 'UTM long sleeved sublimation shirt',
                'long_description' => 'Long sleeved sublimation shirt with UTM design, perfect for cooler weather.',
                'price' => 55.00,
                'status' => 1,
            ],
            [
                'name' => 'UTM Varsity Jacket',
                'slug' => 'utm-varsity-jacket',
                'thumb_image' => 'images/utmmart/varsity.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 45,
                'short_description' => 'UTM varsity jacket',
                'long_description' => 'Classic varsity jacket with UTM branding, perfect for showing school spirit.',
                'price' => 100.00,
                'status' => 1,
            ],
            [
                'name' => 'Sublimation Shirt Type 2',
                'slug' => 'sublimation-shirt-2',
                'thumb_image' => 'images/utmmart/sub2.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 95,
                'short_description' => 'UTM sublimation shirt type 2',
                'long_description' => 'Alternative design sublimation shirt with UTM branding.',
                'price' => 50.00,
                'status' => 1,
            ],
            [
                'name' => 'Muslimah Shirt Maroon',
                'slug' => 'muslimah-shirt-maroon',
                'thumb_image' => 'images/utmmart/musl2.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 75,
                'short_description' => 'UTM maroon muslimah shirt',
                'long_description' => 'Modest and comfortable maroon muslimah shirt with UTM branding.',
                'price' => 50.00,
                'status' => 1,
            ],
            [
                'name' => 'Bucket Hat',
                'slug' => 'bucket-hat',
                'thumb_image' => 'images/utmmart/buckethat.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 120,
                'short_description' => 'UTM bucket hat',
                'long_description' => 'Fashionable bucket hat with UTM logo, perfect for sun protection.',
                'price' => 25.00,
                'status' => 1,
            ],
            [
                'name' => 'Bucket Hat Type 2',
                'slug' => 'bucket-hat-2',
                'thumb_image' => 'images/utmmart/buckethat2.png',
                'vendor_id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'qty' => 120,
                'short_description' => 'UTM bucket hat alternative design',
                'long_description' => 'Alternative design bucket hat with UTM logo, stylish and practical.',
                'price' => 25.00,
                'status' => 1,
            ],
            [
                'name' => 'Metal Pen',
                'slug' => 'metal-pen',
                'thumb_image' => 'images/utmmart/metalpen.png',
                'vendor_id' => 1,
                'category_id' => 3,
                'brand_id' => 1,
                'qty' => 150,
                'short_description' => 'UTM metal pen',
                'long_description' => 'Premium metal pen with UTM branding, elegant and durable.',
                'price' => 38.00,
                'status' => 1,
            ],
            [
                'name' => 'Umbrella',
                'slug' => 'umbrella',
                'thumb_image' => 'images/utmmart/umbrealla.png',
                'vendor_id' => 1,
                'category_id' => 6, // Accessories category
                'brand_id' => 1,
                'qty' => 70,
                'short_description' => 'UTM umbrella',
                'long_description' => 'Sturdy umbrella with UTM logo, perfect for rainy days on campus.',
                'price' => 35.00,
                'status' => 1,
            ],
            [
                'name' => 'Towel',
                'slug' => 'towel',
                'thumb_image' => 'images/utmmart/towel.png',
                'vendor_id' => 1,
                'category_id' => 6,
                'brand_id' => 1,
                'qty' => 60,
                'short_description' => 'UTM towel',
                'long_description' => 'Soft and absorbent towel with UTM branding, perfect for sports or the beach.',
                'price' => 45.00,
                'status' => 1,
            ],
            [
                'name' => 'Document Folder',
                'slug' => 'document-folder',
                'thumb_image' => 'images/utmmart/folder.png',
                'vendor_id' => 1,
                'category_id' => 3,
                'brand_id' => 1,
                'qty' => 100,
                'short_description' => 'UTM document folder',
                'long_description' => 'Professional document folder with UTM logo, perfect for organizing papers.',
                'price' => 16.00,
                'status' => 1,
            ],
            [
                'name' => 'Pencil Pouch',
                'slug' => 'pencil-pouch',
                'thumb_image' => 'images/utmmart/pencilpuoch.png',
                'vendor_id' => 1,
                'category_id' => 3,
                'brand_id' => 1,
                'qty' => 130,
                'short_description' => 'UTM pencil pouch',
                'long_description' => 'Practical pencil pouch with UTM branding, perfect for storing stationery.',
                'price' => 9.00,
                'status' => 1,
            ],
            [
                'name' => 'Lunch Box',
                'slug' => 'lunch-box',
                'thumb_image' => 'images/utmmart/luchbox.png',
                'vendor_id' => 1,
                'category_id' => 6,
                'brand_id' => 1,
                'qty' => 50,
                'short_description' => 'UTM lunch box',
                'long_description' => 'Convenient lunch box with UTM logo, perfect for meals on campus.',
                'price' => 18.00,
                'status' => 1,
            ],
            [
                'name' => 'Fridge Magnet',
                'slug' => 'fridge-magnet',
                'thumb_image' => 'images/utmmart/fridgemagnet.png',
                'vendor_id' => 1,
                'category_id' => 6,
                'brand_id' => 1,
                'qty' => 200,
                'short_description' => 'UTM fridge magnet',
                'long_description' => 'Decorative fridge magnet with UTM design, a small reminder of your university.',
                'price' => 5.00,
                'status' => 1,
            ],
            [
                'name' => 'Golf Umbrella',
                'slug' => 'golf-umbrella',
                'thumb_image' => 'images/utmmart/golfumbrealla.png',
                'vendor_id' => 1,
                'category_id' => 6,
                'brand_id' => 1,
                'qty' => 40,
                'short_description' => 'UTM golf umbrella',
                'long_description' => 'Large golf umbrella with UTM branding, providing excellent coverage in rain.',
                'price' => 35.00,
                'status' => 1,
            ],
            [
                'name' => 'Sports Bottle',
                'slug' => 'sports-bottle',
                'thumb_image' => 'images/utmmart/sportbottle.png',
                'vendor_id' => 1,
                'category_id' => 2,
                'brand_id' => 1,
                'qty' => 85,
                'short_description' => 'UTM sports bottle',
                'long_description' => 'Durable sports bottle with UTM logo, perfect for staying hydrated during workouts.',
                'price' => 29.00,
                'status' => 1,
            ],
            [
                'name' => 'PVC ID Holder',
                'slug' => 'pvc-id-holder',
                'thumb_image' => 'images/utmmart/holder.png',
                'vendor_id' => 1,
                'category_id' => 3,
                'brand_id' => 1,
                'qty' => 250,
                'short_description' => 'UTM PVC ID holder',
                'long_description' => 'Clear PVC ID holder with UTM branding, ideal for keeping your student ID safe.',
                'price' => 7.00,
                'status' => 1,
            ],
            [
                'name' => 'Toiletry Bag',
                'slug' => 'toiletry-bag',
                'thumb_image' => 'images/utmmart/bag.png',
                'vendor_id' => 1,
                'category_id' => 4,
                'brand_id' => 1,
                'qty' => 65,
                'short_description' => 'UTM toiletry bag',
                'long_description' => 'Practical toiletry bag with UTM logo, perfect for organizing personal items.',
                'price' => 11.00,
                'status' => 1,
            ],
        ];

        // Insert all products
        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
